version: "3"
services:
  app:
    container_name: post-service
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - postdb
    depends_on: 
      - postdb
  postdb:
    container_name: postdb
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"