version: 2
jobs:
  api-gateway:
    working_directory: ~/soa2019_group2/service/api-gateway
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          path: ~/soa2019_group2
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/api-gateway .
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/api-gateway
  post-service:
    working_directory: ~/soa2019_group2/service/post
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          path: ~/soa2019_group2
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/post-service .
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/post-service
  search-service:
    working_directory: ~/soa2019_group2/service/search
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          path: ~/soa2019_group2
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/search-service .
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/search-service
  auth-service:
    working_directory: ~/soa2019_group2/service/auth
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          path: ~/soa2019_group2
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/auth-service .
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/auth-service
  review-service:
    working_directory: ~/soa2019_group2/service/review
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          path: ~/soa2019_group2
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/review-service .
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/review-service
  offer-service:
    working_directory: ~/soa2019_group2/service/offer
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          path: ~/soa2019_group2
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/offer-service .
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/offer-service
  profile-service:
    working_directory: ~/soa2019_group2/service/profile
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          path: ~/soa2019_group2
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker
      - run:
          name: Build and Push docker image to asia.gcr.io
          command: |
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/profile-service .
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/profile-service
workflows:
  version: 2
  build_and_push_image:
    jobs:
      - api-gateway:
          filters:
            branches:
              only:
                - master
      - post-service:
          filters:
            branches:
              only:
                - master
      - search-service:
          filters:
            branches:
              only:
                - master
      - auth-service:
          filters:
            branches:
              only:
                - master
      - review-service:
          filters:
            branches:
              only:
                - master
      - offer-service:
          filters:
            branches:
              only:
                - master
      - profile-service:
          filters:
            branches:
              only:
                - master