version: "3"
services:
  app:
    container_name: search-service
    image: gcr.io/soa-project-2/search-service
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - searchdb
    depends_on: 
      - searchdb
  searchdb:
    container_name: searchdb
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"